#!/usr/bin/env python3

"""Convert dotenv-style file into shell-safe export script.

Usage:
    make_service_env.py <input_env> <output_env>
"""

from __future__ import annotations

import re
import shlex
import sys
from pathlib import Path


KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_value(raw: str) -> str:
    value = raw.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        quote = value[0]
        inner = value[1:-1]
        if quote == '"':
            # Basic dotenv-compatible escapes for quoted values.
            inner = (
                inner.replace(r"\n", "\n")
                .replace(r"\r", "\r")
                .replace(r"\t", "\t")
                .replace(r"\"", '"')
                .replace(r"\\", "\\")
            )
        return inner
    return value


def parse_env_file(path: Path) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), 1
    ):
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].lstrip()

        if "=" not in stripped:
            raise ValueError(f"Invalid line {line_number}: expected KEY=VALUE")

        key, raw_value = stripped.split("=", 1)
        key = key.strip()
        if not KEY_RE.match(key):
            raise ValueError(f"Invalid variable name on line {line_number}: {key}")

        value = parse_value(raw_value)
        entries.append((key, value))

    return entries


def render_shell_exports(entries: list[tuple[str, str]]) -> str:
    lines = ["# Generated by make service-sync-env"]
    for key, value in entries:
        lines.append(f"export {key}={shlex.quote(value)}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: make_service_env.py <input_env> <output_env>", file=sys.stderr)
        return 2

    input_path = Path(sys.argv[1]).expanduser().resolve()
    output_path = Path(sys.argv[2]).expanduser().resolve()

    if not input_path.exists():
        print(f"Input env file not found: {input_path}", file=sys.stderr)
        return 1

    try:
        entries = parse_env_file(input_path)
    except ValueError as exc:
        print(f"Error parsing {input_path}: {exc}", file=sys.stderr)
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_shell_exports(entries), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
