use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use console::style;
use dialoguer::{Confirm, Input, Password, Select};

use crate::transcription;

// ──────────────────────────────────────────────────────────────────────────────
// Banner
// ──────────────────────────────────────────────────────────────────────────────

const BANNER: &str = r#"
  ╔════════════════════════════════════════════╗
  ║                                            ║
  ║          🐩  T O O D L E S  🐩             ║
  ║       Telegram × Gemini CLI wrapper        ║
  ║                                            ║
  ╚════════════════════════════════════════════╝
"#;

// ──────────────────────────────────────────────────────────────────────────────
// Config builder
// ──────────────────────────────────────────────────────────────────────────────

struct SetupConfig {
    telegram_bot_token: String,
    allowed_user_ids: Option<String>,
    gemini_cli_path: String,
    gemini_working_dir: Option<String>,
    openai_api_key: Option<String>,
    use_local_transcription: bool,
    models_dir: PathBuf,
    rust_log: String,
}

impl SetupConfig {
    /// Render as `.env` file content.
    fn to_env_string(&self) -> String {
        let mut lines = Vec::new();

        lines.push(
            "# ──────────────────────────────────────────────────────────────────────────────"
                .to_string(),
        );
        lines.push("# Toodles – generated by `toodles --setup`".to_string());
        lines.push(
            "# ──────────────────────────────────────────────────────────────────────────────"
                .to_string(),
        );
        lines.push(String::new());

        lines.push(format!("TELEGRAM_BOT_TOKEN={}", self.telegram_bot_token));
        lines.push(String::new());

        if let Some(ids) = &self.allowed_user_ids {
            lines.push(format!("ALLOWED_USER_IDS={ids}"));
        } else {
            lines.push("# ALLOWED_USER_IDS=".to_string());
        }
        lines.push(String::new());

        lines.push(format!("GEMINI_CLI_PATH={}", self.gemini_cli_path));
        lines.push(String::new());

        if let Some(dir) = &self.gemini_working_dir {
            lines.push(format!("GEMINI_WORKING_DIR={dir}"));
        } else {
            lines.push("# GEMINI_WORKING_DIR=".to_string());
        }
        lines.push(String::new());

        if let Some(key) = &self.openai_api_key {
            lines.push(format!("OPENAI_API_KEY={key}"));
        } else {
            lines.push("# OPENAI_API_KEY=".to_string());
        }
        lines.push(String::new());

        if self.use_local_transcription {
            lines.push("USE_LOCAL_TRANSCRIPTION=true".to_string());
            lines.push(format!("MODELS_DIR={}", self.models_dir.display()));
        } else {
            lines.push("# USE_LOCAL_TRANSCRIPTION=false".to_string());
            lines.push(format!("# MODELS_DIR={}", self.models_dir.display()));
        }
        lines.push(String::new());

        lines.push(format!("RUST_LOG={}", self.rust_log));
        lines.push(String::new());

        lines.join("\n")
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Wizard steps
// ──────────────────────────────────────────────────────────────────────────────

fn step_header(step: u8, total: u8, title: &str) {
    println!();
    println!(
        "  {} {}",
        style(format!("[{step}/{total}]")).cyan().bold(),
        style(title).bold(),
    );
    println!();
}

fn ask_telegram_token() -> Result<String> {
    step_header(1, 7, "Telegram Bot Token");
    println!(
        "  {}",
        style("Get your bot token from @BotFather on Telegram.").dim()
    );
    println!("  {}", style("Format: 123456789:ABCDef...").dim());
    println!();

    let token: String = Password::new()
        .with_prompt("  Bot token")
        .validate_with(|input: &String| -> Result<(), &str> {
            let parts: Vec<&str> = input.split(':').collect();
            if parts.len() == 2
                && parts[0].chars().all(|c| c.is_ascii_digit())
                && !parts[1].is_empty()
            {
                Ok(())
            } else {
                Err("Invalid token format. Expected: <number>:<alphanumeric>")
            }
        })
        .interact()
        .context("Failed to read bot token")?;

    println!("  {} Token saved.", style("✔").green().bold());
    Ok(token)
}

fn ask_allowed_users() -> Result<Option<String>> {
    step_header(2, 7, "User Access Control");
    println!(
        "  {}",
        style("Restrict who can use the bot by specifying Telegram user IDs.").dim()
    );
    println!(
        "  {}",
        style("Leaving this empty allows everyone to use the bot.").dim()
    );
    println!();

    let restrict = Confirm::new()
        .with_prompt("  Restrict access to specific users?")
        .default(false)
        .interact()
        .context("Failed to read confirmation")?;

    if !restrict {
        println!(
            "  {} All users will have access.",
            style("✔").green().bold()
        );
        return Ok(None);
    }

    let ids: String = Input::new()
        .with_prompt("  Allowed user IDs (comma-separated)")
        .validate_with(|input: &String| -> Result<(), &str> {
            let valid = input
                .split(',')
                .all(|s| !s.trim().is_empty() && s.trim().chars().all(|c| c.is_ascii_digit()));
            if valid {
                Ok(())
            } else {
                Err("Enter comma-separated numeric IDs, e.g. 123456789,987654321")
            }
        })
        .interact_text()
        .context("Failed to read user IDs")?;

    let cleaned: String = ids
        .split(',')
        .map(|s| s.trim())
        .collect::<Vec<_>>()
        .join(",");

    println!("  {} Allowed: {cleaned}", style("✔").green().bold());
    Ok(Some(cleaned))
}

fn ask_gemini_cli_path() -> Result<String> {
    step_header(3, 7, "Gemini CLI Path");

    // Try to detect if `gemini` is on PATH
    let found_on_path = std::process::Command::new("which")
        .arg("gemini")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);

    if found_on_path {
        println!(
            "  {} {}",
            style("✔").green().bold(),
            style("gemini found on PATH.").dim()
        );
    } else {
        println!(
            "  {} {}",
            style("⚠").yellow().bold(),
            style("gemini not found on PATH — you may need to specify the full path.").dim()
        );
    }
    println!();

    let path: String = Input::new()
        .with_prompt("  Path to gemini-cli binary")
        .default("gemini".to_string())
        .interact_text()
        .context("Failed to read gemini path")?;

    println!("  {} Using: {path}", style("✔").green().bold());
    Ok(path)
}

fn ask_working_dir() -> Result<Option<String>> {
    step_header(4, 7, "Gemini Working Directory");
    println!(
        "  {}",
        style("Set a working directory for gemini-cli sessions.").dim()
    );
    println!(
        "  {}",
        style("Useful if you want Gemini to have access to a specific project.").dim()
    );
    println!();

    let use_dir = Confirm::new()
        .with_prompt("  Set a custom working directory?")
        .default(false)
        .interact()
        .context("Failed to read confirmation")?;

    if !use_dir {
        println!("  {} Using current directory.", style("✔").green().bold());
        return Ok(None);
    }

    let dir: String = Input::new()
        .with_prompt("  Working directory path")
        .validate_with(|input: &String| -> Result<(), String> {
            if Path::new(input).is_dir() {
                Ok(())
            } else {
                Err(format!("Directory '{}' does not exist", input))
            }
        })
        .interact_text()
        .context("Failed to read working directory")?;

    println!("  {} Using: {dir}", style("✔").green().bold());
    Ok(Some(dir))
}

fn ask_openai_key() -> Result<Option<String>> {
    step_header(5, 7, "Voice Transcription (OpenAI Whisper)");
    println!(
        "  {}",
        style("An OpenAI API key enables cloud voice transcription via OpenAI Whisper.").dim()
    );
    println!(
        "  {}",
        style("This is a fallback if local transcription is not enabled.").dim()
    );
    println!();

    let use_whisper = Confirm::new()
        .with_prompt("  Set up OpenAI Whisper API key?")
        .default(false)
        .interact()
        .context("Failed to read confirmation")?;

    if !use_whisper {
        println!("  {} OpenAI Whisper skipped.", style("✔").green().bold());
        return Ok(None);
    }

    let key: String = Password::new()
        .with_prompt("  OpenAI API key")
        .validate_with(|input: &String| -> Result<(), &str> {
            if input.starts_with("sk-") && input.len() > 10 {
                Ok(())
            } else {
                Err("Key should start with 'sk-' and be longer than 10 characters")
            }
        })
        .interact()
        .context("Failed to read API key")?;

    println!("  {} API key saved.", style("✔").green().bold());
    Ok(Some(key))
}

/// Returns (use_local_transcription, models_dir).
fn ask_local_transcription() -> Result<(bool, PathBuf)> {
    step_header(6, 7, "Local Transcription (Parakeet V3)");
    println!(
        "  {}",
        style("Parakeet V3 enables fully offline voice transcription.").dim()
    );
    println!(
        "  {}",
        style(format!(
            "Model size: ~{} MB (downloaded once).",
            transcription::MODEL_SIZE_MB
        ))
        .dim()
    );
    println!(
        "  {}",
        style("No API keys needed — everything runs locally.").dim()
    );
    println!();

    let enable = Confirm::new()
        .with_prompt("  Enable local transcription?")
        .default(true)
        .interact()
        .context("Failed to read confirmation")?;

    let default_dir = transcription::default_models_dir();

    if !enable {
        println!(
            "  {} Local transcription disabled.",
            style("✔").green().bold()
        );
        return Ok((false, default_dir));
    }

    let models_dir: String = Input::new()
        .with_prompt("  Models directory")
        .default(default_dir.display().to_string())
        .interact_text()
        .context("Failed to read models directory")?;
    let models_dir = PathBuf::from(&models_dir);

    // Download the model
    if transcription::is_model_downloaded(&models_dir) {
        println!("  {} Model already downloaded.", style("✔").green().bold());
    } else {
        let download_now = Confirm::new()
            .with_prompt("  Download Parakeet V3 model now?")
            .default(true)
            .interact()
            .context("Failed to read confirmation")?;

        if download_now {
            println!();
            println!("  {} Downloading Parakeet V3...", style("⬇").cyan().bold());

            // Run the async download using the existing tokio runtime.
            tokio::task::block_in_place(|| {
                tokio::runtime::Handle::current()
                    .block_on(transcription::download_model(&models_dir))
            })?;

            println!("  {} Model ready!", style("✔").green().bold());
        } else {
            println!(
                "  {} {}",
                style("⚠").yellow().bold(),
                style("Model will be downloaded on first bot start.").yellow()
            );
        }
    }

    Ok((true, models_dir))
}

fn ask_log_level() -> Result<String> {
    step_header(7, 7, "Log Level");

    let levels = vec!["error", "warn", "info", "debug", "trace"];
    let default_idx = 2; // "info"

    let selection = Select::new()
        .with_prompt("  Select log level")
        .items(&levels)
        .default(default_idx)
        .interact()
        .context("Failed to read log level")?;

    let level = levels[selection].to_string();
    println!("  {} Log level: {level}", style("✔").green().bold());
    Ok(level)
}

// ──────────────────────────────────────────────────────────────────────────────
// Preview & write
// ──────────────────────────────────────────────────────────────────────────────

fn preview_config(config: &SetupConfig) {
    println!();
    println!(
        "  {}",
        style("┌─────────────────────────────────────────────┐").cyan()
    );
    println!(
        "  {}",
        style("│           Configuration Summary             │").cyan()
    );
    println!(
        "  {}",
        style("└─────────────────────────────────────────────┘").cyan()
    );
    println!();

    let mask = |s: &str| -> String {
        if s.len() <= 8 {
            "••••••••".to_string()
        } else {
            format!("{}••••••••", &s[..4])
        }
    };

    println!(
        "  {:<24} {}",
        style("Bot Token:").bold(),
        style(mask(&config.telegram_bot_token)).dim()
    );
    println!(
        "  {:<24} {}",
        style("Allowed Users:").bold(),
        config
            .allowed_user_ids
            .as_deref()
            .unwrap_or("all (unrestricted)")
    );
    println!(
        "  {:<24} {}",
        style("Gemini CLI:").bold(),
        config.gemini_cli_path
    );
    println!(
        "  {:<24} {}",
        style("Working Dir:").bold(),
        config
            .gemini_working_dir
            .as_deref()
            .unwrap_or("(current directory)")
    );
    println!(
        "  {:<24} {}",
        style("OpenAI Key:").bold(),
        config
            .openai_api_key
            .as_ref()
            .map(|k| mask(k))
            .unwrap_or_else(|| "not set".to_string())
    );
    println!(
        "  {:<24} {}",
        style("Local Transcription:").bold(),
        if config.use_local_transcription {
            style("enabled (Parakeet V3)").green().to_string()
        } else {
            "disabled".to_string()
        }
    );
    if config.use_local_transcription {
        println!(
            "  {:<24} {}",
            style("Models Dir:").bold(),
            config.models_dir.display()
        );
    }
    println!("  {:<24} {}", style("Log Level:").bold(), config.rust_log);

    println!();
}

fn write_env_file(config: &SetupConfig) -> Result<()> {
    let env_path = Path::new(".env");

    if env_path.exists() {
        println!(
            "  {} {}",
            style("⚠").yellow().bold(),
            style("A .env file already exists!").yellow(),
        );

        let choices = vec!["Overwrite", "Back up & overwrite", "Cancel"];
        let selection = Select::new()
            .with_prompt("  What would you like to do?")
            .items(&choices)
            .default(1)
            .interact()
            .context("Failed to read selection")?;

        match selection {
            0 => { /* overwrite directly */ }
            1 => {
                let backup = ".env.backup";
                std::fs::copy(env_path, backup)
                    .with_context(|| format!("Failed to create backup at {backup}"))?;
                println!(
                    "  {} Backup saved to {}",
                    style("✔").green().bold(),
                    style(backup).underlined()
                );
            }
            _ => {
                println!("  {} Setup cancelled.", style("✘").red().bold());
                return Ok(());
            }
        }
    }

    let content = config.to_env_string();
    std::fs::write(env_path, &content).context("Failed to write .env file")?;

    println!();
    println!(
        "  {} {}",
        style("✔").green().bold(),
        style(".env file written successfully!").green().bold()
    );
    println!();
    println!("  {}", style("Start the bot with:").dim());
    println!("    {}", style("cargo run --release").cyan().bold());
    println!();

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_env_string_all_fields() {
        let config = SetupConfig {
            telegram_bot_token: "123456789:ABCDef".to_string(),
            allowed_user_ids: Some("111,222".to_string()),
            gemini_cli_path: "/usr/local/bin/gemini".to_string(),
            gemini_working_dir: Some("/home/user/project".to_string()),
            openai_api_key: Some("sk-1234567890abcdef".to_string()),
            use_local_transcription: true,
            models_dir: PathBuf::from("/home/user/.local/share/toodles/models"),
            rust_log: "debug".to_string(),
        };

        let env_string = config.to_env_string();
        let expected = "\
# ──────────────────────────────────────────────────────────────────────────────
# Toodles – generated by `toodles --setup`
# ──────────────────────────────────────────────────────────────────────────────

TELEGRAM_BOT_TOKEN=123456789:ABCDef

ALLOWED_USER_IDS=111,222

GEMINI_CLI_PATH=/usr/local/bin/gemini

GEMINI_WORKING_DIR=/home/user/project

OPENAI_API_KEY=sk-1234567890abcdef

USE_LOCAL_TRANSCRIPTION=true
MODELS_DIR=/home/user/.local/share/toodles/models

RUST_LOG=debug
";
        assert_eq!(env_string, expected);
    }

    #[test]
    fn test_to_env_string_missing_optional_fields() {
        let config = SetupConfig {
            telegram_bot_token: "987654321:XYZ".to_string(),
            allowed_user_ids: None,
            gemini_cli_path: "gemini".to_string(),
            gemini_working_dir: None,
            openai_api_key: None,
            use_local_transcription: false,
            models_dir: PathBuf::from("/models"),
            rust_log: "info".to_string(),
        };

        let env_string = config.to_env_string();
        let expected = "\
# ──────────────────────────────────────────────────────────────────────────────
# Toodles – generated by `toodles --setup`
# ──────────────────────────────────────────────────────────────────────────────

TELEGRAM_BOT_TOKEN=987654321:XYZ

# ALLOWED_USER_IDS=

GEMINI_CLI_PATH=gemini

# GEMINI_WORKING_DIR=

# OPENAI_API_KEY=

# USE_LOCAL_TRANSCRIPTION=false
# MODELS_DIR=/models

RUST_LOG=info
";
        assert_eq!(env_string, expected);
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Public entry point
// ──────────────────────────────────────────────────────────────────────────────

/// Run the interactive setup wizard.
pub fn run_setup() -> Result<()> {
    println!("{}", style(BANNER).cyan().bold());
    println!(
        "  {}",
        style("Interactive setup wizard — let's configure your bot!").bold()
    );

    let telegram_bot_token = ask_telegram_token()?;
    let allowed_user_ids = ask_allowed_users()?;
    let gemini_cli_path = ask_gemini_cli_path()?;
    let gemini_working_dir = ask_working_dir()?;
    let openai_api_key = ask_openai_key()?;
    let (use_local_transcription, models_dir) = ask_local_transcription()?;
    let rust_log = ask_log_level()?;

    let config = SetupConfig {
        telegram_bot_token,
        allowed_user_ids,
        gemini_cli_path,
        gemini_working_dir,
        openai_api_key,
        use_local_transcription,
        models_dir,
        rust_log,
    };

    preview_config(&config);

    let confirmed = Confirm::new()
        .with_prompt("  Write this configuration to .env?")
        .default(true)
        .interact()
        .context("Failed to read confirmation")?;

    if confirmed {
        write_env_file(&config)?;
    } else {
        println!("  {} Setup cancelled.", style("✘").red().bold());
    }

    Ok(())
}
